### ISSUE TITLE
Preparing Certificate CSR in Azure Key Vault

### ISSUE THREAD

**Issue by smoonlee** [az-acme/az-acme-cli#14]
Get the following error when running the az-acme within a Function App

INFO: Preparing Certificate CSR in Azure Key Vault.
Unhandled exception. Azure.RequestFailedException: The request URI contains an invalid name: www.mbops.io
Status: 400 (Bad Request)
ErrorCode: BadParameter

Content:
{"error":{"code":"BadParameter","message":"The request URI contains an invalid name: www.domain.tld"}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: westeurope
x-ms-client-request-id: 
x-ms-request-id: 
x-ms-keyvault-service-version: 1.9.444.2
x-ms-keyvault-network-info: conn_type=Ipv4;addr=0.0.0.0;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Fri, 24 Jun 2022 14:49:51 GMT
Content-Length: 100
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Certificates.CertificateClient.GetCertificateOperation(String certificateName, CancellationToken cancellationToken)
   at AzAcme.Core.Providers.KeyVault.AzureKeyVaultCertificateStore.GetExistingOperationOrNull(String name) in /home/runner/work/az-acme-cli/az-acme-cli/src/AzAcme.Core/Providers/KeyVault/AzureKeyVaultCertificateStore.cs:line 86
   at AzAcme.Core.Providers.KeyVault.AzureKeyVaultCertificateStore.Prepare(CertificateRequest request) in /home/runner/work/az-acme-cli/az-acme-cli/src/AzAcme.Core/Providers/KeyVault/AzureKeyVaultCertificateStore.cs:line 37
   at AzAcme.Cli.Commands.OrderCommand.OnExecute(OrderOptions opts) in /home/runner/work/az-acme-cli/az-acme-cli/src/AzAcme.Cli/Commands/OrderCommand.cs:line 84
   at AzAcme.Cli.Commands.Command`1.Execute(T opts) in /home/runner/work/az-acme-cli/az-acme-cli/src/AzAcme.Cli/Commands/Command.cs:line 21
   at AzAcmi.Program.Main(String[] args) in /home/runner/work/az-acme-cli/az-acme-cli/src/AzAcme.Cli/Program.cs:line 36
   at AzAcmi.Program.<Main>(String[] args)
Aborted (core dumped)

**Comment by ross-mcdermott** [comment]
@smoonlee could you share the cli parameters being used (or equivalent) for reproduction please?

**Comment by smoonlee** [comment]
Hey,  Sorry should have put it in the opening post 


./az-acme order \
--server https://acme-v02.api.letsencrypt.org/directory \
--dns-provider $AzProvider \
--azure-dns-zone $AzDnsZone \
--key-vault-uri $AzKeyVault \
--account-secret $AzAccSecret \
--renew-within-days 30 \
--certificate www.mbops.io \
--subject www.mbops.io

**Comment by ross-mcdermott** [comment]
Thanks @smoonlee it looks like the name of the certificate isn't valid. Try replacing dots with dashes for the --certificate parameter, this is the name of the cert object in key vault, doesn't need to be the same as the subject.

See example here:
https://azacme.dev/docs/operations#order-or-renew

**Comment by smoonlee** [comment]
Morning, So do you mean like this?

./az-acme order `
--server https://acme-v02.api.letsencrypt.org/directory `
--dns-provider $AzProvider `
--azure-dns-zone $AzDnsZone `
--key-vault-uri $AzKeyVault `
--account-secret $AzAccSecret `
--renew-within-days 30 `
--certificate [www.mbops.io](http://www.mbops.io/) `
--subject [www.mbops.io](http://www.mbops.io/)

**Comment by ross-mcdermott** [comment]
No, see example from documentation and how the certificate name and subject are different. Certificate name is the name of the object stored in keyvault.

```
az-acme order \
        --server https://acme-v02.api.letsencrypt.org/directory \
        --key-vault-uri https://kvazacmedev.vault.azure.net/ \
        --certificate demo-certificate \
        --subject stgle01.demo.azacme.dev \
        --sans stgle002.demo.azacme.dev stgle003.demo.azacme.dev \
        --account-secret reg-le-stg-azacme-dev \
        --dns-provider Azure \
        --azure-dns-zone /subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.Network/dnszones/demo.azacme.dev \
        --renew-within-days 30
```

So your certificate parameter value would be something like:

```
--certificate www-mbops-io \
--subject www.mbops.io
```

This is a naming restriction azure has in place around names for certificates (and secrets and keys) entries in keyvault.

The name of the certificate does not relate to the subject or SANs for the certificate.

**Comment by smoonlee** [comment]
Ahhh, Sorry yes I see! haven't had coffee yet! 

Let me try this and see what happens :)

**Comment by smoonlee** [comment]
![image](https://user-images.githubusercontent.com/22956963/177115260-b2bd5159-c873-4434-be0c-ecfff73f8a7f.png)

So Sorry Ross! Thanks for your help!
