### ISSUE TITLE
urn:ietf:params:acme:error:malformed: Unable to update challenge :: authorization must be pending exceptions

### ISSUE THREAD

**Issue by camptatopenmars** [az-acme/az-acme-cli#18]
Mostly linking to my pull request: [https://github.com/az-acme/az-acme-cli/pull/17]

My theory is that azure DNS has some sort of latency between completing the api to add a challenge TXT record and it being visible to the wider internet.  Some sort of propagation delay.  Calling  AzAcme.Core.Providers.CertesAcme.CertesAcmeProvider.ValidateChallenge() 'too soon' would cause letencrypt to return an error indicating NXDOMAIN.

I suspect there is a second sort of error that the first call might return that is handled in some manner within  AzAcme.Core.Providers.CertesAcme.CertesAcmeProvider.ValidateChallenge(), but is actually fatal since letsencrypt has in some manner marked the challenge as invalid and a subsequent call to  AzAcme.Core.Providers.CertesAcme.CertesAcmeProvider.ValidateChallenge() fails with the below stack and error.

{
"type": "urn:ietf:params:acme:error:malformed",
"detail": "Method not allowed",
"status": 405
}

Both errors (NXDOMAIN and HTTP 405 responses) have the following stack within az-acme.

Unhandled exception. Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/chall-v3/131571447226/y38ebQ'.
urn:ietf:params:acme:error:malformed: Unable to update challenge :: authorization must be pending
at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, IAcmeContext context, Uri location, Object entity, Boolean ensureSuccessStatusCode)
at Certes.Acme.ChallengeContext.Validate()
at AzAcme.Core.Providers.CertesAcme.CertesAcmeProvider.ValidateChallenges(Order order)
at AzAcme.Cli.Commands.OrderCommand.<>c__DisplayClass5_0.<b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Spectre.Console.LiveDisplay.<>c__DisplayClass17_0.<b__0>d.MoveNext() in //src/Spectre.Console/Live/LiveDisplay.cs:line 80
--- End of stack trace from previous location ---
at Spectre.Console.LiveDisplay.<>c__DisplayClass18_01.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 110 --- End of stack trace from previous location --- at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func1 func) in //src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
at Spectre.Console.LiveDisplay.StartAsync[T](Func2 func) in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 98 at Spectre.Console.LiveDisplay.StartAsync(Func2 func) in /_/src/Spectre.Console/Live/LiveDisplay.cs:line 78
at AzAcme.Cli.Commands.OrderCommand.WaitForVerificationWithTable(Order order, IAcmeDirectory directory, Int32 attempts, Int32 delaySeconds)
at AzAcme.Cli.Commands.OrderCommand.OnExecute(OrderOptions opts)
at AzAcme.Cli.Commands.Command`1.Execute(T opts)
at AzAcmi.Program.Main(String[] args)
at AzAcmi.Program.

(String[] args)

**Comment by ross-mcdermott** [comment]
@camptatopenmars i've added related fixes to https://github.com/az-acme/az-acme-cli/releases/tag/v0.3 - could you please confirm it resolves this?

**Comment by camptatopenmars** [comment]
> @camptatopenmars i've added related fixes to https://github.com/az-acme/az-acme-cli/releases/tag/v0.3 - could you please confirm it resolves this?

I just got back from some hiking...  I'll see if I can find a few this week to try it out.  Thanks!

**Comment by scabana** [comment]
Using 0.3 doesn't seem to fix it.
